#!/bin/bash

#VERSION="9088345"
VERSION="0.2.0-beta-2-SNAPSHOT"
INSTALL_DIR=${1:-$(pwd)}
OPSYS=${2:-"linux"}

echo "Installing into $INSTALL_DIR"
echo "Assuming operating system $OPSYS"

# check for operating system
if [[ "$OPSYS" == "linux" ]]; then
  MEM=$(cat /proc/meminfo | grep MemTotal | sed s/^MemTotal:\\\s*\\\|\\\s\\+[^\\\s]*$//g)
  MEM=$(($MEM/2/1024/1024))
elif [[ "$OPSYS" == "osx" ]]; then
  # sysctl returns total hardware memory size in bytes
  MEM=$(sysctl hw.memsize | grep hw.memsize | sed s/hw.memsize://g)
  MEM=$(($MEM/2/1024/1024/1024))
else
  echo "ERROR - Operating system (arg2) must be either linux or osx - EXITING"
  exit
fi

# mvn clean install
# temporary workaround for openjdk plus surefire bug
_JAVA_OPTIONS=-Djdk.net.URLClassPath.disableClassPathURLCheck=true mvn clean install
mvn -Dmdep.outputFile=cp.txt -Dmdep.includeScope=runtime dependency:build-classpath

echo '#!/bin/bash' > sciview
echo '' >> sciview
echo "JAR=\$HOME/.m2/repository/sc/iview/sciview/${VERSION}/sciview-${VERSION}.jar" >> sciview
echo 'java \' >> sciview
echo "  -Xmx${MEM}g \\" >> sciview
echo '  -XX:+UseConcMarkSweepGC \' >> sciview
echo -n '  -cp $JAR:' >> sciview
echo -n $(cat cp.txt) >> sciview
echo ' \' >> sciview
echo '  sc.iview.Main "$@"' >> sciview

chmod a+x sciview

rm cp.txt

mkdir -p $INSTALL_DIR
mv sciview $INSTALL_DIR/
